/* Header for module newasm, generated by p2c */
#ifndef NEWASM_H
#define NEWASM_H


#ifdef NEWASM_G
# define vextern
#else
# define vextern extern
#endif


#define na_scale        65536L

#define na_rbias        1023



/*32 bits*/

typedef Char na_chararray[];


typedef union na_word {
  short i;
  unsigned short u;
  struct {
    Char c1, c2;
  } U7;
  struct {
    uchar ub1, ub2;
  } U8;
  struct {
    char sb1, sb2;
  } U9;
  unsigned short b4;
  unsigned short b2;
  unsigned short b;
  Char str[2];
} na_word;

typedef na_word na_wordarray[];

typedef Anyptr na_long;
#define na_long na_longword
#include <stdint.h>
typedef union na_long {
  int32_t i;
  struct {
    short i1, i2;
  } U2;
  struct {
    short x, y;
  } U3;
  struct {
    unsigned short u1, u2;
  } U4;
  struct {
    char fill1;
    Signed int s3 : 24;
  } U5;
  struct {
    uchar fill2;
    unsigned u3 : 24;
  } U6;
  Char c[4];
  uchar ub[4];
  int32_t sb;
  uint32_t b4;
  uint32_t b2;
  uint32_t b;
  Anyptr sr;
  Char str[4];
  Char *sp;
  Anyptr p;
  double *rp;
  na_word *wp;
  union na_long *lp;
  union na_quadword *qp;
  struct na_strlistrec *sl;
  Char *cap;
  na_word *wap;
  union na_long *lap;
  union na_quadword *qap;
  struct {
    unsigned sign : 1, mag : 31;
  } U27;
  int32_t *setp;
  struct {
    na_word w1, w2;
  } U99;
} na_long;

#undef na_long
typedef na_long na_longwordarray[];

typedef union na_quadword {
  struct {
    int32_t i1, i2;
  } U1;
  short si[4];
  unsigned short su[4];
  Char c[8];
  uchar ub[8];
  short sb[4];
  uchar b4[8];
  uchar b2[8];
  uchar b[8];
  struct {
    Anyptr sr1, sr2;
  } U13;
  double r;
  Char str[8];
  struct {
    Char *sp1, *sp2;
  } U16;
  struct {
    Anyptr p1, p2;
  } U17;
  struct {
    double *rp1, *rp2;
  } U18;
  struct {
    na_word *wp1, *wp2;
  } U19;
  struct {
    na_long *lp1, *lp2;
  } U20;
  struct {
    union na_quadword *qp1, *qp2;
  } U21;
  struct {
    struct na_strlistrec *sl1, *sl2;
  } U22;
  struct {
    Char *cap1, *cap2;
  } U23;
  struct {
    na_word *wap1, *wap2;
  } U24;
  struct {
    na_long *lap1, *lap2;
  } U25;
  struct {
    union na_quadword *qap1, *qap2;
  } U26;
  _PROCEDURE pr;
  struct {
    unsigned rsign : 1, rexp : 11, rmant1 : 20;
    int32_t rmant2;
  } U28;
  na_word w[4];
  struct {
    na_long l1, l2;
  } U99;
} na_quadword;

typedef na_quadword na_quadwordarray[];

typedef struct na_strlistrec {
  struct na_strlistrec *next;
  na_long value;   /*user-defined*/
  Char kind;   /*user-defined*/
  Char len;   /*for internal use*/
  Char s[256];   /*not entirely allocated*/
} na_strlistrec;



/* p2c: newasm.imp, line 161:
 * Note: Absolute-addressed variable P_nil2 was generated [116] */
extern Anyptr *P_nil2;


typedef na_strlistrec na_strlist;

extern Void na_fillbyte PP((int32_t *d, int32_t w, int32_t n));
extern Void na_fillword PP((int32_t *d, int32_t w, int32_t n));
extern Void na_fill PP((int32_t *d, int32_t w, int32_t n));
extern Void na_fillp PP((Anyptr d, int32_t w, int32_t n));
extern Void na_move PP((int32_t *s, int32_t *d, int32_t size));
extern Void na_movep PP((Anyptr s, Anyptr d, int32_t size));
extern Void na_exch PP((int32_t *s, int32_t *d, int32_t size));
extern Void na_exchp PP((Anyptr s, Anyptr d, int32_t size));
extern int32_t na_comp PP((int32_t *a, int32_t *b, int32_t size));
extern int32_t na_compp PP((Anyptr a, Anyptr b, int32_t size));
extern int32_t na_scaneq PP((int32_t *s, int32_t what, int32_t size));
extern int32_t na_scaneqp PP((Anyptr s, int32_t what, int32_t size));
extern int32_t na_scanne PP((int32_t *s, int32_t what, int32_t size));

extern int32_t na_scannep PP((Anyptr s, int32_t what, int32_t size));
extern Void na_new PP((Anyptr *p, int32_t s));
extern Void na_dispose PP((Anyptr *p, int32_t s));
extern Void na_alloc PP((Anyptr *p, int32_t s));
extern Void na_outeralloc PP((Anyptr *p, int32_t s, int32_t parframe));
extern Void na_free PP((Anyptr *p));

extern int32_t na_memavail PV();
extern int32_t na_and PP((int32_t x, int32_t y));
extern int32_t na_bic PP((int32_t x, int32_t y));
extern int32_t na_or PP((int32_t x, int32_t y));
extern int32_t na_xor PP((int32_t x, int32_t y));
extern int32_t na_not PP((int32_t x));
extern boolean na_mask PP((int32_t x, int32_t y));
extern boolean na_test PP((int32_t n, int32_t x));
extern Void na_set PP((int32_t n, int32_t *x));
extern Void na_clear PP((int32_t n, int32_t *x));
extern int32_t na_log2 PP((int32_t n));
extern int32_t na_po2 PP((int32_t n));
extern int32_t na_lobits PP((int32_t n));
extern int32_t na_hibits PP((int32_t n));
extern int32_t na_asl PP((int32_t n, int32_t x));
extern int32_t na_lsl PP((int32_t n, int32_t x));

extern int32_t na_rol PP((int32_t n, int32_t x));
extern Void na_bfclr PP((int32_t *v, int32_t offset, int32_t size));
extern Void na_bfset PP((int32_t *v, int32_t offset, int32_t size));
extern Void na_bfchg PP((int32_t *v, int32_t offset, int32_t size));
extern boolean na_bftst PP((int32_t *v, int32_t offset, int32_t size));
extern Void na_bffill PP((int32_t *v, int32_t offset, int32_t size, int b));
extern Void na_bfmove PP((int32_t *s, int32_t soff, int32_t *d, int32_t doff, int32_t size));
extern Void na_bfrev PP((int32_t *v, int32_t offset, int32_t size));
extern Void na_bfins PP((int32_t *v, int32_t offset, int32_t size, int32_t val));
extern int32_t na_bfextu PP((int32_t *v, int32_t offset, int32_t size));
extern int32_t na_bfexts PP((int32_t *v, int32_t offset, int32_t size));
extern int32_t na_bfffo PP((int32_t *v, int32_t offset, int32_t size));
extern int32_t na_bfffz PP((int32_t *v, int32_t offset, int32_t size));

extern int32_t na_bfcount PP((int32_t *v, int32_t offset, int32_t size));
extern int32_t na_setcard PP((int32_t *s));
extern int32_t na_setlast PP((int32_t *s));
extern int32_t na_setnext PP((int32_t *s, int32_t offset));

extern int32_t na_setnextnot PP((int32_t *s, int32_t offset));
extern int32_t P_imax PP((int32_t a, int32_t b));
extern int32_t P_imin PP((int32_t a, int32_t b));
extern int32_t P_isgn PP((int32_t a));
extern double P_rmax PP((double a, double b));
extern double P_rmin PP((double a, double b));

extern int32_t P_rsgn PP((double a));
extern int32_t P_imax2 PP((int32_t a, int32_t b));
extern int32_t P_imin2 PP((int32_t a, int32_t b));
extern int32_t P_imax3 PP((int32_t a, int32_t b, int32_t c));
extern int32_t P_imin3 PP((int32_t a, int32_t b, int32_t c));
extern int32_t P_imax4 PP((int32_t a, int32_t b, int32_t c, int32_t d));
extern int32_t P_imin4 PP((int32_t a, int32_t b, int32_t c, int32_t d));
extern Void P_iswap2 PP((int32_t *a, int32_t *b));
extern Void P_isort2 PP((int32_t *a, int32_t *b));
extern Void P_isort3 PP((int32_t *a, int32_t *b, int32_t *c));
extern Void P_isort4 PP((int32_t *a, int32_t *b, int32_t *c, int32_t *d));
extern int32_t P_ibound PP((int32_t min, int32_t i, int32_t max));
extern boolean P_ibetween PP((int32_t min, int32_t i, int32_t max));
extern boolean P_ibetweenm PP((int32_t min, int32_t i, int32_t max, int32_t margin));
extern Void P_iamin PP((int32_t *min, int32_t i));
extern Void P_iamax PP((int32_t *max, int32_t i));

extern Void P_iaminmax PP((int32_t *min, int32_t *max, int32_t i));
extern int32_t P_isqrt PP((int32_t n));

extern int32_t P_ipow PP((int32_t y, int32_t x));
extern int32_t na_add PP((int32_t a, int32_t b));
extern int32_t na_sub PP((int32_t a, int32_t b));
extern Void na_addc PP((int32_t *a, int32_t b, boolean *c));
extern Void na_subc PP((int32_t *a, int32_t b, boolean *c));
extern int32_t na_smul PP((int32_t a, int32_t b));
extern int32_t na_umul PP((int32_t a, int32_t b));
extern na_quadword na_smul64 PP((int32_t a, int32_t b));
extern na_quadword na_umul64 PP((int32_t a, int32_t b));
extern Void na_udiv64 PP((na_quadword *q, int32_t *r, na_quadword a, int32_t b));

extern Void na_sdiv64 PP((na_quadword *q, int32_t *r, na_quadword a, int32_t b));
extern Void P_return PV();
extern Void P_returnb PP((int b));
extern Void P_returnc PP((int c));
extern Void P_returni PP((int32_t i));
extern Void P_returnp PP((Anyptr p));

extern Void P_returnr PP((double r));
extern Anyptr na_rtosr PP((double r));

extern double na_srtor PP((Anyptr sr));
extern double na_stor PP((int32_t s));
extern int32_t na_rtos PP((double r));
extern int32_t na_sm PP((int32_t a, int32_t b));
extern int32_t na_sd PP((int32_t a, int32_t b));
extern int32_t na_strunc PP((int32_t s));
extern int32_t na_sround PP((int32_t s));
extern int32_t na_sint PP((int32_t s));
extern int32_t na_sfrac PP((int32_t s));
extern int32_t na_itos PP((int32_t s));

extern int32_t na_ssqrt PP((int32_t s));
extern Void na_compint PP((na_long a, na_long b, int32_t *res));
extern Void na_compstr PP((na_long a, na_long b, int32_t *res));


extern Void na_qsort PP((na_long *a, int32_t n, _PROCEDURE comp));
extern Void strsafeappend PP((Char *s, Char *s2));
extern Void strappendc PP((Char *s, int ch));
extern Char *strupper PP((Char *Result, Char *s));
extern Char *strlower PP((Char *Result, Char *s));
extern Char charupper PP((int ch));
extern Char charlower PP((int ch));
extern Char *strpart PP((Char *Result, Char *s, int32_t first, int32_t last));
extern Char *strlast PP((Char *Result, Char *s, int32_t num));
extern Char *strljust PP((Char *Result, Char *s, int32_t wid));
extern Char *strrjust PP((Char *Result, Char *s, int32_t wid));
extern Char *strcjust PP((Char *Result, Char *s, int32_t wid));
extern boolean strbegins PP((Char *s1, Char *s2));
extern boolean strends PP((Char *s1, Char *s2));
extern boolean strcibegins PP((Char *s1, Char *s2));
extern boolean strciends PP((Char *s1, Char *s2));
extern boolean strequal PP((Char *s1, Char *s2));
extern int32_t strsubcmp PP((int32_t n, Char *s1, int32_t i1, Char *s2, int32_t i2));
extern boolean strcisubcmp PP((int32_t n, Char *s1, int32_t i1, Char *s2, int32_t i2));
extern Void strsubst PP((Char *repl, Char *s, int32_t index, int32_t size));
extern Char *strint PP((Char *Result, int32_t i));
extern Char *strint2 PP((Char *Result, int32_t i, int32_t w));
extern Char *strreal PP((Char *Result, double r));
extern Char *strchar PP((Char *Result, int ch));
extern int32_t strreadint PP((Char *s));
extern double strreadreal PP((Char *s));
extern int32_t strposb PP((Char *s1, Char *s2, int32_t i));
extern int32_t strposc PP((Char *s1, int ch, int32_t i));
extern int32_t strposcset PP((Char *s1, Char *s2, int32_t i));
extern int32_t strposbcset PP((Char *s1, Char *s2, int32_t i));
extern int32_t strcipos2 PP((Char *s1, Char *s2, int32_t i));
extern int32_t strciposb PP((Char *s1, Char *s2, int32_t i));
extern boolean strcontains PP((Char *s1, Char *s2));
extern boolean strsubset PP((Char *s1, Char *s2));
extern boolean strcommon PP((Char *s1, Char *s2));
extern int32_t strlenv PP((Char *s));
extern Char *strhex PP((Char *Result, int32_t i, int32_t w));
extern Char *strbinary PP((Char *Result, int32_t i, int32_t w));
extern Char *strdate PP((Char *Result, Char *opts));
extern Void strword PP((Char *s, Char *word));
extern Void strword2 PP((Char *s, Char *word));
extern Void strcomment PP((Char *s, Char *bracket));
extern Void strcompress PP((Char *s, Char *chars, int all));
extern Void strdispose PP((Char **sp));

extern Void strchange PP((Char **sp, Char *s));
extern Void strlist_init PP((na_strlistrec **base));
extern na_strlistrec *strlist_find PP((na_strlistrec *base, Char *s));
extern na_strlistrec *strlist_cifind PP((na_strlistrec *base, Char *s));
extern Void strlist_change PP((na_strlistrec **base, na_strlistrec **ptr,
			       Char *s));
extern Void strlist_remove PP((na_strlistrec **base, Char *s));
extern Void strlist_delete PP((na_strlistrec **base, na_strlistrec *ptr));
extern Void strlist_dispose PP((na_strlistrec **ptr));
extern Void strlist_empty PP((na_strlistrec **base));
extern Void strlist_copy PP((na_strlistrec **dest, na_strlistrec *src));

extern Void na_bfand PP((int32_t *s, int32_t soff, int32_t *d, int32_t doff, int32_t size));
extern Void na_bfbic PP((int32_t *s, int32_t soff, int32_t *d, int32_t doff, int32_t size));
extern Void na_bfor PP((int32_t *s, int32_t soff, int32_t *d, int32_t doff, int32_t size));
extern Void na_bfxor PP((int32_t *s, int32_t soff, int32_t *d, int32_t doff, int32_t size));
extern Char *strnew PP((Char *s));
extern na_strlist *strlist_add PP((na_strlist **base, Char *s));
extern na_strlist *strlist_append PP((na_strlist **base, Char *s));
extern na_strlist *strlist_insert PP((na_strlist **base, Char *s));

extern Void strlist_dump PP((FILE *f, na_strlistrec *base));


#undef vextern

extern char * strcpy_overlap(char * dst, char * src);

#endif /*NEWASM_H*/

/* End. */
